version: 0.2

phases:
  install:
    runtime-versions:
       python: 3.7
  build:
    commands:
      - sam package --s3-bucket cf-templates-1sn9jbxojocwx-us-east-1 --output-template-file packaged-template.yaml --template-file template.yaml
      
