version: 0.2

phases:
  install:
    runtime-versions:
       python: 3.7
    commands:
      - echo Entered the install phase...     
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade aws-sam-cli
  build:
    commands:
      - sam package --s3-bucket cf-templates-1ss44bnseato0-us-east-2 --output-template-file packaged-template.yaml --template-file template.yaml
      
