AWSTemplateFormatVersion: '2010-09-09'
Description: codepipeline

Parameters:

  GitHubOAuthToken:
    Type: String
    NoEcho: true
    MinLength: 40
    MaxLength: 40
    AllowedPattern: '[a-z0-9]*'

  GitHubOwner:
    Type: String
    Default: Harika444
    AllowedPattern: "[A-Za-z0-9-]+"

  GitHubRepo:
    Type: String
    Default: serverless-survey
    AllowedPattern: "[A-Za-z0-9-]+"

  GitHubBranch:
    Type: String
    Default: master
    AllowedPattern: "[A-Za-z0-9-]+"


Resources:
  PipelineArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineArtifactsBucket
      RestartExecutionOnUpdate: true
      RoleArn: arn:aws:iam::940838980384:role/CodepipelineRole
      Stages:
      - Name: Source
        Actions:
        - Name: Source
          InputArtifacts: []
          ActionTypeId:
            Category: Source
            Owner: ThirdParty
            Version: 1
            Provider: GitHub
          OutputArtifacts:
          - Name: SourceCode
          Configuration:
            Owner: !Ref GitHubOwner
            Repo: !Ref GitHubRepo
            Branch: !Ref GitHubBranch
            PollForSourceChanges: false
            OAuthToken: !Ref GitHubOAuthToken
          RunOrder: 1

      - Name: Build
        Actions:
        - Name: Build
          ActionTypeId:
            Category: Build
            Owner: AWS
            Version: 1
            Provider: CodeBuild
          OutputArtifacts:
          - Name: BuildCode
          InputArtifacts:
          - Name: SourceCode
          Configuration:
            ProjectName: !Ref CodeBuildProject
          RunOrder: 1
          
      - Name: veracode
        Actions:
        - Name: Build
          ActionTypeId:
            Category: Build
            Owner: AWS
            Version: 1
            Provider: CodeBuild
          InputArtifacts:
          - Name: BuildArtifacts
          Configuration:
            ProjectName: Dev-Author-Veracode-CodeBuildProject
          RunOrder: 1
           
      - Name: CreateChangeSet
        Actions:
        - Name: Deploy
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: CloudFormation
            Version: "1"
          Configuration:
            ActionMode: CHANGE_SET_REPLACE
            Capabilities: CAPABILITY_NAMED_IAM
            ChangeSetName: serverless-survey-Changeset
            RoleArn: arn:aws:iam::940838980384:role/CodePipelineLambdaRole
            StackName: serverless-survey
            TemplatePath: "BuildCode::packaged-template.yaml"
          InputArtifacts:
          - Name: BuildCode
          RunOrder: 1
          
      - Name: ExecuteChangeSet
        Actions:
        - Name: Deploy       
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: CloudFormation
            Version: "1"
          Configuration:
            ActionMode: CHANGE_SET_EXECUTE
            ChangeSetName: serverless-survey-Changeset    
            RoleArn: arn:aws:iam::940838980384:role/CodePipelineLambdaRole
            StackName: serverless-survey
          RunOrder: 2
          
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: no_artifacts
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:4.0
        Type: LINUX_CONTAINER
      Name: !Sub ${AWS::StackName}-CodeBuildProject
      ServiceRole: arn:aws:iam::940838980384:role/CodeBuildRole
      Source:
        Type: GITHUB_ENTERPRISE
        Auth:
          Resource: !Ref GitHubOAuthToken
          Type: OAUTH
        Location: https://github.com/Harika444/serverless-survey.git
        BuildSpec: buildspec.yml

  GithubWebhook:
    Type: 'AWS::CodePipeline::Webhook'
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Ref GitHubOAuthToken
      RegisterWithThirdParty: 'true'
      Filters:
      - JsonPath: "$.ref"
        MatchEquals: refs/heads/{Branch}
      TargetPipeline: !Ref CodePipeline
      TargetAction: Source
      TargetPipelineVersion: !GetAtt CodePipeline.Version
